# Generated by Django 4.2.10 on 2024-02-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_order_product_expense_order_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expense',
            field=models.ManyToManyField(blank=True, to='app.expense'),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(blank=True, to='app.product'),
        ),
    ]
