# Generated by Django 4.2.10 on 2024-02-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_order_expense_alter_order_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Group',
        ),
    ]
