# Generated by Django 4.2.10 on 2024-02-11 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_tag_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tag',
            new_name='group',
        ),
    ]
