# Generated by Django 4.2.10 on 2024-02-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_tag_invoice_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='name',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.AddField(
            model_name='expense',
            name='sub_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='amt',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.CharField(blank=True, choices=[('Product', 'Product'), ('Expense', 'Expense')], null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
