# Generated by Django 4.2.10 on 2024-02-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_name_expense_category_remove_expense_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='description',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expense',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
